### PR TITLE
Add pipeline details 

### LINKED ISSUE #170: Create a pipeline details view
This view should show details about the current pipeline:
- [ ] Trigger token
- [ ] Name
- [ ] Last run time
- [ ] Location
- [ ] Remote fork url
- [ ] Branch
- [ ] Last log entry
- [ ] ...?

### PR DESCRIPTION
**Pull request by Shivakishore14**
Resolves #170 
Added the pipeline details table in the pipeline details view page.

Here is a screenshot
image

Let me know if this is good.

### CODE REVIEW

**Comment by Skarlso** [comment]
Hi @Shivakishore14! First of all, thank you very much for your contribution! Second, can you show as well where this is triggered from and how that looks like?

Cheers!

**Comment by michelvocks** [comment]
Hi @Shivakishore14,

this looks very good! Thank you for your contribution!

Only a very tiny change I would like to see is the underlined space between the last-run-number and the "[success]" output in the "Last Run" column. It looks a bit cleaner if the space char is not underlined.

Otherwise, it looks great!

Cheers,
Michel

**Comment by Shivakishore14** [comment]
@michelvocks yes, I have fixed that now.

@Skarlso I have added a new table to detail.vue page (as shown in the screenshot above), The data is populated from the pipeline and pipelineRun service calls which were already present in the page.

**Comment by Skarlso** [comment]
Oh duh. I thought it's a different view. Appologies. :D

**Pull request merged**
