### PR TITLE
Pipeline parameters

### LINKED ISSUE #24: Pipeline parameters
When triggering a pipeline it would be nice to be able to specify input parameters. This would allow users to have dynamic configuration for their pipelines.

An example would be a pipeline that runs database migrations and it needs an input of the database name.

### PR DESCRIPTION
**Pull request by michelvocks**
Fixes #24

### CODE REVIEW

**Comment by michelvocks** [comment]
ping @Skarlso 
It's ready for review. We should merge #67 before so this PR doesn't include it anymore.
For testing you can use following pipeline: https://github.com/michelvocks/gaia-test-pipeline/tree/dependson

**Comment by Skarlso** [comment]
Excellent! Looks good on a first run, I'll give it a manual. :)

**Comment by Skarlso** [comment]
So, unfortunately I ran into a couple of problems @michelvocks. :/

I created two pipelines with the same repository. Once I set values to one, the other just flashed in the argument window and then puff, made it disappear immediately and went on running the pipeline. It came out as empty value in the logs.

Second, the variables aren't cleared after once specifying them. Meaning, once you defined them, you can't every define them again, because they are already saved in cache I think, and so the asking module just flashes in and then immediately disappears.

The Vault stuff is working nicely however. :)

**Comment by michelvocks** [comment]
Oh thanks for the report. Let me try to reproduce and fix it 🤗

**Comment by michelvocks** [comment]
@Skarlso I rebased and fixed your reported bugs. Try it again and let me know 🤗 
I also updated my test pipeline to point back to gaia-pipeline repositories: https://github.com/michelvocks/gaia-test-pipeline/tree/master

**Pull request merged**
