### PR TITLE
Small Makefile modification to bring down binary size.

### PR DESCRIPTION
**Pull request by Skarlso**
This brings down the binary size from 21MB to 11MB.

Also, I'm planning on adding a coverage report for all packages in `test-cover` so hold off on merging until then if you so please. :)

### CODE REVIEW

**Comment by michelvocks** [comment]
Awesome. 😊

Usually you start the title with WIP (work in progress) so everyone knows that this PR is still in progress. 
Let me know when it's ready to be merged. :smile:

**Comment by Skarlso** [comment]
Good point. :)

I have several small Prs now. What I'll do I think is merge them together rather. The make file and a test cleanup together make sense. The way it is right now is too fractured. I'll pull these Prs into one test fix / refactor one. It will be much easier to manage. :)

**Comment by Skarlso** [comment]
Oh never mind. You merged the others. :DDDD I'll pull them in here and make the coverage reporter. :)

**Comment by michelvocks** [comment]
That sounds great. :smile:

**Comment by Skarlso** [comment]
The beginnings:

```bash
❯ go test ./... --coverprofile=cover.out
?   	github.com/gaia-pipeline/gaia	[no test files]
?   	github.com/gaia-pipeline/gaia/cmd/gaia	[no test files]
?   	github.com/gaia-pipeline/gaia/handlers	[no test files]
ok  	github.com/gaia-pipeline/gaia/pipeline	6.957s	coverage: 2.5% of statements
?   	github.com/gaia-pipeline/gaia/plugin	[no test files]
ok  	github.com/gaia-pipeline/gaia/scheduler	0.018s	coverage: 16.4% of statements
ok  	github.com/gaia-pipeline/gaia/store	0.027s	coverage: 30.0% of statements
```

**Comment by Skarlso** [comment]
This is done for now. :)

**Pull request merged**
