### PR TITLE
Fix scaling of pipelines on overview (#73)

### PR DESCRIPTION
**Pull request by speza**

### CODE REVIEW

**Comment by Skarlso** [comment]
Hi! First of all, thanks for this contribution! 

Second, this now anchors the divs to each other. Making them stick, so when the screen is large, they get elongated. Meaning the span and widen. 

I honestly think that that doesn't look so good. A better option is to make the divs re-arrange on larger screens so they take up the place, but do that without changing the size of the dive, but re-arranging themselves.

This is how it looks like now on wider view mode:

screenshot 2018-10-16 at 21 53 29

What do you think @michelvocks?

**Comment by Skarlso** [comment]
I'm by no means good at front-end stuff, but what I'm talking about is basically and auto-balancing css grid. There are a couple of articles about it around, if you don't happen to know that stuff, it's a great learning opportunity. :) Good luck! 👍

**Comment by speza** [comment]
I am also by no means a front-end guy! Was just looking for a ‘quick win’ while in some downtime. I just looked for a quick solution using the UI framework already in-place. Probably a good thing to know so I will look into a better solution soon.

**Comment by speza** [comment]
@Skarlso let me know what you think of this latest change.

**Comment by Skarlso** [comment]
@speza excellent!! It works lovely. :)

**Comment by michelvocks** [comment]
@speza Thanks a lot for your contribution. This is really cool! ❤️

**Pull request merged**
