### PR TITLE
[WIP] Swagger for the API

### PR DESCRIPTION
**Pull request by Skarlso**
Started working on Swaggering up the API. Also updated to echo v4 for maximum module usage. ( and because the handler is using v4... grump grump )

### CODE REVIEW

**Comment by Skarlso** [comment]
Deals with #150.

**Comment by Skarlso** [comment]
This is going to be a massive amount of frigging typing... :D :D :D 

Screenshot 2019-04-07 at 21 35 15
Screenshot 2019-04-07 at 21 35 06

**Comment by Skarlso** [comment]
This also needs a docs Pr describing how to update the swagger doc.

For now, I'm following the annotation outlined here: https://github.com/swaggo/swag#declarative-comments-format

To generate the docs, stand in the root folder and run:
```
swag init -g ./cmd/gaia/main.go
```

**Comment by michelvocks** [comment]
Cool. Good job @Skarlso 

Do you know what the outcome is when you generate the docs? Is it a static HTML website?
We are currently using netlify as a host for our docs + website and want to make sure that we can still use that. 😄

**Comment by Skarlso** [comment]
I think I can get Swagger to generate static HTML. At least I know there is an option for that. :D I have no idea how well that works. :)

Right now, as you can see, it's a go file actually. :)

**Comment by Skarlso** [comment]
BTW. So right now basically the app is hosting its own documentation. Basically if you have a running Gaia instance you can access the api by going to gaia.org/swagger. Bumm instant living docs. Also useful for development.

But I agree that a static generated doc on a hosted site would be also cool.

**Comment by michelvocks** [comment]
@Skarlso Yeah that's cool. But in the end, we need a hosted website where you can check the API from Gaia. 👍

**Comment by Skarlso** [comment]
Oh Gods. So much conflict on this now. :D

**Comment by Skarlso** [comment]
I'm going to close this one and re-open with the few changes. It's easier than trying to resolve all the conflicts.

**Comment by Skarlso** [comment]
Actually wasn't that hard. The go.mod and go.sum file might be off.

**Comment by Skarlso** [comment]
Alright. Going to continue doing this.

**Comment by Skarlso** [comment]
Hah, made it recognise the auth method.
```
curl -X GET "http://gaia-pipeline.io/api/v1/users" -H "accept: application/json" -H "Authorization: Bearer ASDFASDF="
```

Swagger generated get there.

**Pull request closed without merging**
