### PR TITLE
Echo groups (fix #252)

### LINKED ISSUE #252: Simplify the non restricted endpoint matches
@speza has already something here: https://github.com/gaia-pipeline/gaia/compare/master...speza:echo-groups

### PR DESCRIPTION
**Pull request by speza**
So this utilises echo groups to manage what endpoints have the auth middleware applied. This is nice a clean and lets us avoid using the nonProtectedPathsPrefix and nonProtectedPaths slices on every request.

Fixes #252.

### CODE REVIEW

**Comment by Skarlso** [comment]
@speza Did you have a chance to test this with a production build of Gaia as well making sure all elements like favico and such are displayed correctly?

**Comment by speza** [comment]
> @speza Did you have a chance to test this with a production build of Gaia as well making sure all elements like favico and such are displayed correctly?

@Skarlso what is the best way to build a production version? Build the Dockerfile?

**Comment by Skarlso** [comment]
@speza I actually started testing this for you. :) I wanted to make sure the build process still works anyways. Don't worry about it. :)

**Comment by Skarlso** [comment]
Tested this with a release. Seems to work fine. :) I used the Helm charts and a kubernetes release.

**Pull request merged**
