### PR TITLE
Adding swagger

### PR DESCRIPTION
**Pull request by Skarlso**
Generate the docs:

```
swag init -g ./cmd/gaia/main.go
```

Then view:

https://gaia.whatever.com/api/v1/swagger/index.html

### CODE REVIEW

**Comment by Skarlso** [comment]
This will now fix #150.

**Comment by Skarlso** [comment]
@speza Doing this I found a little mix-up in the rbac endpoints. :) It looks like you were using the wrong handler for one of the endpoints also the naming and comments of some other handlers were wrong which I didn't spot either. :D I fixed them in this PR. :)

**Comment by Skarlso** [comment]
Hey @speza.

Do we still use this? `apiAuthGrp.GET("permission", PermissionGetAll)`.

**Comment by Skarlso** [comment]
Nice! This works perfectly fine. :)

**Comment by speza** [comment]
Ah nice! It was so much manual work I can believe I got something wrong haha. 

That old permissions endpoint is still being used if anyone used legacy perms. Still used in the UI until we deprecate it.

**Pull request merged**
