### PR TITLE
[WIP] docker support

### LINKED ISSUE #92: Support pipeline execution in docker container
Currently, pipelines are directly executed on the host system. It would be helpful if pipelines could be executed in their own docker container which can be removed after execution (like a sandbox).

### PR DESCRIPTION
**Pull request by michelvocks**
Fixes #92

### CODE REVIEW

**Comment by prologic** [comment]
Any progres on this diff?

**Comment by michelvocks** [comment]
@prologic 
This has been down-priorized (additional language support has currently higher priority) but is still one if the most important features.

Expect this to be finished by end of january.

**Comment by michelvocks** [comment]
Sorry @prologic but I had to block this feature now until #46 is done. I listed some why's in the main issue #92.

**Comment by Skarlso** [comment]
This has been done by https://github.com/gaia-pipeline/gaia/pull/201

**Comment by prologic** [comment]
That's tantasic!

**Pull request closed without merging**
